openapi: 3.0.0
info:
  title: MyLab Project Service API
  version: 1.0.0
servers:
  - url: https://api.mylab.example/v1
paths:
  /projects:
    post:
      summary: Create project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '201':
          description: Project created
  /projects/{id}/lineage:
    get:
      summary: Get project lineage
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lineage graph
components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        status:
          type: string
